OrchardCMS/OrchardCore.Commerce

Abstractions/CommerceSettings.cs, AdminMenu.cs, Drivers/CommerceSettingsDisplayDriver.cs, Drivers/PricePartDisplayDriver.cs, Money/Currency.cs, Money/CurrencyProvider.cs, OrchardCore.Commerce.csproj, Permissions.cs, Services/CommerceSettingsConfiguration.cs, Services/MoneyService.cs, Startup.cs, ViewModels/CommerceSettingsViewModel.cs, Views/CommerceSettings.Edit.cshtml, Views/PricePart.Edit.cshtml
I've implemented a few small changes for the PricePart.
- Fixed a NullReferenceException when creating a new content item that contains a PricePart.
- Added SEK (Swedish krona) currency. Thinking about making an editor for maintaining currency data.
- Added a settings page with option to configure default currency.
I'm interested in participating in the development of the OrchardCore.Commerce module.
=> PricePart default currency

Drivers/ProductAttributeFieldDriver.cs, Fields/ProductAttributeField.cs, Settings/ProductAttributeFieldSettings.cs, Settings/ProductAttributeFieldSettingsDriver.cs, Startup.cs, ViewModels/EditProductAttributeFieldViewModel.cs, ViewModels/TextProductAttributeSettingsViewModel.cs, Views/BooleanProductAttributeFieldSettings.Edit.cshtml, Views/BooleanProductAttributeField_Edit.cshtml, Views/NumericProductAttributeFieldSettings.Edit.cshtml, Views/NumericProductAttributeField_Edit.cshtml, Views/TextProductAttributeFieldSettings.Edit.cshtml, Views/TextProductAttributeField_Edit.cshtml
Product attributes are defined as fields that usually have nothing to edit in the product editor. The parameters of the attributes are usually set-up at the content type definition level, as settings of the fields.
Built-in product attributes are Boolean, numeric, and text (which includes predefined values, and thus can handle enums, flags, and combos). This should be enough for most cases, but is, as usual, extensible.
The front-end for those new fields will be introduced with the shopping cart: each attribute will participate as adding information to the "add to cart" action. For example, adding two shirts of size M.
=> Introduce product attributes

Drivers/PricePartDisplayDriver.cs, MoneyDataType/LegacyAmountConverter.cs, Settings/CommerceSettingsConfiguration.cs, Startup.cs
Fix reading known currencies and add back initialization of default currency configured in settings.
I've only done tests with the PricePart, The changes are not verified with the PriceVariantsPart.
The main issue was that when a known currency was saved only the CurrencyIsoCode is saved. When reading it back the missing values resulted in it being handled as unknown.
Added back the CommerceSettingsConfiguration so that the default currency configured for the site is taken into consideration.
=> Currency serialization fixes

MoneyDataType/Abstractions/ICurrency.cs, MoneyDataType/AmountConverter.cs, MoneyDataType/Currency.cs, MoneyDataType/Currency.extra.cs, MoneyDataType/KnownCurrencyTable.cs, MoneyDataType/LegacyAmountConverter.cs, Services/MoneyService.cs, Settings/CommerceSettingsDisplayDriver.cs, ViewModels/CommerceSettingsViewModel.cs, Views/CommerceSettings.Edit.cshtml
Changed to use the english currency name. We got random results with the name on different machines.
=> Native currency names

Abstractions/IPredefinedValuesProductAttributeFieldSettings.cs, Drivers/ProductPartDisplayDriver.cs, Services/ShoppingCartHelpers.cs, Settings/CommerceSettingsDisplayDriver.cs
Adding the symbol and ISO code in the drop-down so currencies are easily identified even without a translation of the currency name.
=> Default currency settings formatting

Drivers/PricePartDisplayDriver.cs, Handlers/PricePartHandler.cs, Models/PricePart.cs, Settings/CurrencySelectionModeEnum.cs, Settings/PricePartSettings.cs, Settings/PricePartSettingsDisplayDriver.cs, Startup.cs, ViewModels/PricePartSettingsViewModel.cs, Views/PricePartSettings.Edit.cshtml
Added a settings option on PricePart that makes it possible to configure/restrict what currencies are possible to select when entering data for a product. This way rules can be setup when the product type is designed and make the entered data more reliable.
**Possible options**:
1. All Currencies - The only option available today. If not configured when attaching the PricePart to a type this is the default.
2. Default Currency - Restricts the PricePart to the configured default currency. Useful for sites that only sells in a single market/region.
3. Specific Currency - The idea with this option is to make it possible to restrict the currency that can be selected for PricePart to a specific currency. Right now this option is disabled.
On a product type multiple PricePart objects can be …
=> PricePart currency configuration.

Drivers/PricePartDisplayDriver.cs, Handlers/PricePartHandler.cs, Models/PricePart.cs
Instance level PricePartSettings were not handled correctly. When multiple PricePart (named) instances were added to a type all got the same settings.
=> Fix: TypePartSettings were not unique per instance

Abstractions/ICurrencySelector.cs, Abstractions/IMoneyService.cs, CommerceConstants.cs, Drivers/PricePartDisplayDriver.cs, Manifest.cs, Migrations/PriceMigrations.cs, Recipes/MultiCurrencyProduct.recipe.json, Services/MoneyService.cs, Services/NullCurrencySelector.cs, Services/PriceProvider.cs, Settings/CommerceSettings.cs, Settings/CommerceSettingsConfiguration.cs, Settings/CommerceSettingsCurrencySelector.cs, Settings/CommerceSettingsDisplayDriver.cs, Startup.cs, ViewModels/CommerceSettingsViewModel.cs, ViewModels/PricePartViewModel.cs, Views/CommerceSettings.Edit.cshtml, Views/PricePart.cshtml
Implemented logic to be able to select the currency prices are shown in on the site. It builds on the configuration settings that were added to the PricePart.
**There are two implementations added**: 
1. NullCurrencySelector - Don't affect anything. DefaultCurrency returned from MoneyService will be displayed.
2. CommerceSettingsCurrencySelector - Will use currency configured in commerce settings. Can be different from the default site currency configured. Good for testing.
Update in Startup.cs which implementation will be used.
**Notes**:
- Changed PricePart to be reusable by default.
- Updated PriceProvider to work with multiple currencies on a product. The selected currency is used for showing prices in the shopping cart.
- Added a sample recipe for a product with multiple PriceParts.
=> Currency selector

MoneyDataType/AmountConverter.cs, MoneyDataType/KnownCurrencyTable.cs, MoneyDataType/LegacyAmountConverter.cs
Made a small change to the serialization of PricePart data. Currently data for the unspecified currency is stored. 
```json
"PricePart": {
"Price": {
"value": 999.0,
"nativename": "Unspecified",
"englishname": "Unspecified",
"symbol": "---",
"iso": "---",
"currency": "SEK"
}
},
```
Added it to the currency table to make it known and serialize like this.
```json
"PricePart": {
"Price": {
"value": 99.0,
"currency": "SEK"
}
},
```
=> Currency serialization

OrchardCore.Commerce.Tests/CurrencyTests.cs
Custom currency without regional/culture configuration fails in countries with decimal comma (,).
Changed test to pass with current system settings. Don't think it will be common use case to add currencies not available in the system.
=> Currency Test failing in countries with decimal comma (,)

src/Modules/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs, src/Modules/OrchardCore.Commerce/Settings/CommerceSettings.cs, src/Modules/OrchardCore.Commerce/Settings/CommerceSettingsCurrencySelector.cs, src/Modules/OrchardCore.Commerce/Views/PricePart.cshtml
=> OCC-17: Inconsistent currency configuration after setup

Directory.Build.props, src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj, src/Modules/OrchardCore.Commerce/Settings/CommerceSettingsDisplayDriver.cs, src/Modules/OrchardCore.Commerce/Views/AddressField_Edit.cshtml
[NEST-319](https://lombiq.atlassian.net/browse/NEST-319)
Fixes #129
=> NEST-319: Upgrade remaining Orchard Core packages to 1.4.0 and fix settings and editor crash when Localization feature is enabled

src/Modules/OrchardCore.Commerce/Controllers/PaymentController.cs, src/Modules/OrchardCore.Commerce/Drivers/StripeApiSettingsDisplayDriver.cs, src/Modules/OrchardCore.Commerce/Permissions.cs
=> OCC-32: Add Checkout permission

src/Modules/OrchardCore.Commerce/Views/OrderPart.cshtml, src/Modules/OrchardCore.Commerce/Views/OrderPart_Edit.cshtml
SITE-24
Line items were not displayed when there were no charges. This can be annoying in some debug situtation. Now for displaying line items we check the line items, not the charges.
=> SITE-24: Fix bug related to displaying line items inside orders without charges

src/Libraries/OrchardCore.Commerce.AddressDataType/AddressFormatterProvider.cs, src/Libraries/OrchardCore.Commerce.AddressDataType/Region.cs, src/Libraries/OrchardCore.Commerce.AddressDataType/Regions.cs, src/Modules/OrchardCore.Commerce/Abstractions/IRegionService.cs, src/Modules/OrchardCore.Commerce/Drivers/RegionSettingsDisplayDriver.cs, src/Modules/OrchardCore.Commerce/Extensions/RegionExtensions.cs, src/Modules/OrchardCore.Commerce/Services/RegionService.cs, src/Modules/OrchardCore.Commerce/Views/Checkout.cshtml, test/OrchardCore.Commerce.Tests.UI/Tests/RegionTests/PersistenceRegionSettingsTests.cs
=> OCC-97: Country or region selector wrong spelling

docs/resources/libraries/README.md, src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj, src/Modules/OrchardCore.Commerce.Promotion/OrchardCore.Commerce.Promotion.csproj, src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj, src/Modules/OrchardCore.Commerce/Drivers/PriceVariantsPartDisplayDriver.cs, src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj, src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj, test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
NEST-362
Continuation of [skrypt/1.5](https://github.com/OrchardCMS/OrchardCore.Commerce/tree/skrypt/1.5), now that Lombiq submodules are updated to OC 1.5
=> NEST-362: Upgrade to Orchard Core 1.5

.github/workflows/publish-cloudsmith.yml, src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj, test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj, test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OCC-152
- ✔️ `dotnet pack` no longer crashes.
- ✔️ [Now the preview packages are correctly versioned (1.0.1) on CloudSmith.](https://cloudsmith.io/~orchardcore/repos/commerce/packages/)
Fixes #286
=> OCC-152: Publish to NuGet step fails in publish workflow

src/Modules/OrchardCore.Commerce/Constants/ContentTypes.cs, src/Modules/OrchardCore.Commerce/Controllers/UserController.cs, src/Modules/OrchardCore.Commerce/Extensions/HttpContextExtensions.cs, src/Modules/OrchardCore.Commerce/Extensions/UserManagerExtensions.cs, src/Modules/OrchardCore.Commerce/Migrations/UserDetailsMigrations.cs, src/Modules/OrchardCore.Commerce/Models/UserDetailsPart.cs, src/Modules/OrchardCore.Commerce/Services/PaymentService.cs, src/Modules/OrchardCore.Commerce/Startup.cs, src/Modules/OrchardCore.Commerce/Views/User/Details.cshtml, test/OrchardCore.Commerce.Tests.UI/Tests/UserTests/UserPersistenceTests.cs
=> OCC-169: Add user editor for the non-address checkout fields too

src/Modules/OrchardCore.Commerce/Controllers/PaymentController.cs, src/Modules/OrchardCore.Commerce/Handlers/OrderPermissionsAuthorizationHandler.cs, src/Modules/OrchardCore.Commerce/Permissions.cs, src/Modules/OrchardCore.Commerce/Startup.cs
=> OCC-67: Add OrderPart permissions

.github/actions/spelling/allow/occ.txt, src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Samples.Product.recipe.json, src/Modules/OrchardCore.Commerce/Services/DiscountProvider.cs, src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_OldPrice.cshtml, test/OrchardCore.Commerce.Tests.UI/Tests/PromotionTests/PromotionBehaviourTests.cs
[OCC-173](https://lombiq.atlassian.net/browse/OCC-173)
Fixes #322
=> OCC-173: Discount is not applied if there is also another not discounted product in the shopping cart

OrchardCore.Commerce.sln, docs/resources/libraries/README.md
Add docs/resources/libraries/Readme.md in solution.
In OC, we created and OrchardCore.Docs.csproj in order to include all the .md files in the solution.
=> Orchard Core version 1.7.0 in libraries

src/Modules/OrchardCore.Commerce/Activities/CartUpdatedEvent.cs, src/Modules/OrchardCore.Commerce/Controllers/ShoppingCartController.cs, src/Modules/OrchardCore.Commerce/Drivers/CartEventActivityDisplayDriverBase.cs, src/Modules/OrchardCore.Commerce/Events/InventoryShoppingCartEvents.cs, src/Modules/OrchardCore.Commerce/Services/ShoppingCartSerializer.cs, src/Modules/OrchardCore.Commerce/Startup.cs, src/Modules/OrchardCore.Commerce/Views/ProductPart.cshtml, src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_Quantity.cshtml, test/OrchardCore.Commerce.Tests.UI/Tests/InventoryTests/InventoryBehaviourTests.cs, test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/OrderSuccessTests.cs
[OCC-183](https://lombiq.atlassian.net/browse/OCC-183)
Fixes #340
=> OCC-183: Check 'Maximum Order Quantity' update on Cart

.readthedocs.yml
Error on build:
`Invalid configuration option "build.os": build not found`
=> Fix ReadTheDocs build error

.github/actions/spelling/excludes.txt, Directory.Build.props, Directory.Packages.props, Nuget.config, OrchardCore.Commerce.sln, src/Libraries/OrchardCore.Commerce.Abstractions/OrchardCore.Commerce.Abstractions.csproj, src/Libraries/OrchardCore.Commerce.MoneyDataType/OrchardCore.Commerce.MoneyDataType.csproj, src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj, src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj, src/Modules/OrchardCore.Commerce.Payment.Stripe/OrchardCore.Commerce.Payment.Stripe.csproj, src/Modules/OrchardCore.Commerce.Payment/OrchardCore.Commerce.Payment.csproj, src/Modules/OrchardCore.Commerce.Promotion/OrchardCore.Commerce.Promotion.csproj, src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj, src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj, src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj, test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj, test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj, test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs, test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
[OCC-218](https://lombiq.atlassian.net/browse/OCC-218)
Since this project will never have submodules it makes sense to use _Directory.Packages.props_ and get rid of the tedium of upgrading each csproj individually. Going forward we'll only have more project files so it's best to do it now than later.
Fixes #404
=> OCC-218: Update NuGet packages and migrate to centralized package management

docs/requirements.txt
Update docs requirements.
I updated the settings on Crowdin to not display this banner: 
On merge, it will trigger a new build and should update the docs taking this setting into account.
=> Docs requirements

src/Modules/OrchardCore.Commerce/Views/ProductListPart.Filters.cshtml
[ADHOC-475](https://lombiq.atlassian.net/browse/ADHOC-475)
There's no related issue; it was connected to another development task of mine where I implemented something similar. I encountered this bug and realized it will be an issue here, too.
=> ADHOC-475: Fixing that tenant URL prefix is not applied in the product list filter form

src/Modules/OrchardCore.Commerce.Payment.Stripe/EndPoints/Api/StripeEndpoint.cs, src/Modules/OrchardCore.Commerce/Endpoints/Api/PaymentEndpoint.cs, src/Modules/OrchardCore.Commerce/Endpoints/Api/ShoppingCartLineEndpoint.cs
[OFFI-99](https://lombiq.atlassian.net/browse/OFFI-99)
=> OFFI-99: Inferred parameters are not always recognized correctly causing exceptions

src/Modules/OrchardCore.Commerce.Payment.Stripe/Abstractions/IStripePaymentService.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Models/StripePaymentProviderData.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentProvider.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs
=> Pass PaymentIntentId to Client for convenience of API calling

Directory.Packages.props, src/Libraries/OrchardCore.Commerce.AddressDataType/Region.cs, src/Libraries/OrchardCore.Commerce.AddressDataType/Regions.cs, src/Modules/OrchardCore.Commerce/Drivers/TaxRateTaxPartDisplayDriver.cs, src/Modules/OrchardCore.Commerce/Events/PromotionShoppingCartEvents.cs, src/Modules/OrchardCore.Commerce/Events/TaxShoppingCartEvents.cs, src/Modules/OrchardCore.Commerce/Models/PromotionAndTaxProviderContext.cs, test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/BehaviorOrderTests.cs, test/OrchardCore.Commerce.Tests.UI/UITestBase.cs, test/OrchardCore.Commerce.Tests/AddressTests.cs
[OCC-302](https://lombiq.atlassian.net/browse/OCC-302)
Fixes #503
=> OCC-302: Fix Serializing the Region type using System.Text.Json throws an exception

src/Modules/OrchardCore.Commerce.Payment.Stripe/Manifest.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Startup.cs, src/Modules/OrchardCore.Commerce/Startup.cs, src/OrchardCore.Commerce.Web/NLog.config
[OCC-333](https://lombiq.atlassian.net/browse/OCC-333)
Fixes #548
=> OCC-333: Fix dependency resolution errors in SubscriptionStripeWebhookEventHandler

src/Modules/OrchardCore.Commerce.Payment.Exactly/Services/ExactlyPaymentProvider.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentProvider.cs, src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs, src/Modules/OrchardCore.Commerce.Payment/Abstractions/IPaymentProvider.cs, src/Modules/OrchardCore.Commerce.Payment/Endpoints/Api/PaymentEndpoint.cs, src/Modules/OrchardCore.Commerce.Payment/Services/DummyPaymentProvider.cs, src/Modules/OrchardCore.Commerce.Payment/Services/PaymentService.cs, src/Modules/OrchardCore.Commerce.Payment/ViewModels/PaymentViewModel.cs
=> Need to consider passing shoppingCartId at more places
