Recipes/Product.recipe.json

Use the latest OC format for the product recipe.

Product recipe: new format

---

Nuget.config
OrchardCore.Commerce.Tests/Fakes/FakeContentDefinitionManager.cs
OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce.sln
OrchardCore.Commerce/OrchardCore.Commerce.csproj
README.md
SampleWebApp/SampleWebApp.csproj

Added nuget.config to Orchard Core Preview feed.
Changed to use latest rc2 build by default.

Add nuget.config

---

OrchardCore.Commerce/Drivers/PricePartDisplayDriver.cs
OrchardCore.Commerce/Serialization/PrioritizedPriceConverter.cs

Changed instances of ICurrency using == and != operators to use the .Equals() method instead to fix issue #74.

Fix for issue #74

---

Nuget.config
OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

https://github.com/OrchardCMS/OrchardCore/releases/tag/v1.0.0

Update packages to OrchardCore 1.0.0

---

OrchardCore.Commerce.Tests/Fakes/FakeContentManager.cs

Add new member to FakeContentManager. Breaking tests after update to Orchard Core 1.0.

New method in IContentManager interface.

---

OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/Controllers/ShoppingCartController.cs
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

Update packages to Orchard Core version `1.1.0`.

Orchard Core 1.1.0

---

OrchardCore.Commerce.Tests/CurrencyTests.cs
OrchardCore.Commerce.Tests/MoneyServiceTests.cs

I copied/isolated the approach by @Skrypt to fix/remove these tests on windows

fix 2 tests on windows

---

MoneyDataType/Currency.extra.cs

Fix warning in Currency.extra.cs

---

MoneyDataType/MoneyDataType.csproj
OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

https://github.com/OrchardCMS/OrchardCore/releases/tag/v1.2.0

Orchard Core 1.2.0

---

OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

https://www.nuget.org/packages/OrchardCore.Application.Cms.Core.Targets/1.2.1

OrchardCore 1.2.1

---

OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

https://github.com/OrchardCMS/OrchardCore/releases/tag/v1.2.2

Orchard Core 1.2.2

---

MoneyDataType/MoneyDataType.csproj
OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
OrchardCore.Commerce/OrchardCore.Commerce.csproj
SampleWebApp/SampleWebApp.csproj

https://www.nuget.org/packages/OrchardCore.Application.Cms.Core.Targets/1.3.0

OrchardCore 1.3.0

---

src/Modules/OrchardCore.Commerce/Handlers/UniqueSkuValidationHandler.cs
src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Tests.Setup.recipe.json
src/Modules/OrchardCore.Commerce/Recipes/Product.recipe.json
src/Modules/OrchardCore.Commerce/Startup.cs
test/OrchardCore.Commerce.Tests.UI/Tests/PriceVariantsPartTests/ValidationPriceVariantsTests.cs

OCC-25: SKUs should be globally unique

---

src/Modules/OrchardCore.Commerce/Assets/Scripts/stripe-card-form.js
src/Modules/OrchardCore.Commerce/Views/Payment/Index.cshtml
src/Modules/OrchardCore.Commerce/Views/Payment/Success.cshtml

OCC-27: Stripe payments error out on tenants

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

Add files related to contributions.

Contributing, Code of conduct

---

src/Libraries/OrchardCore.Commerce.MoneyDataType/Extensions/JObjectExtensions.cs
src/Modules/OrchardCore.Commerce/Abstractions/IProductAttributeValue.cs
src/Modules/OrchardCore.Commerce/Serialization/ProductAttributeValueConverter.cs
src/Modules/OrchardCore.Commerce/Views/OrderPart_Edit.cshtml

OCC-28: Order part breaks when it contains products with attributes

---

src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Tests.Setup.recipe.json
test/OrchardCore.Commerce.Tests.UI/Tests/TaxTests/TaxBehaviourTests.cs

OCC-80: UI tests don't use fixed culture

---

src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj
src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj

NEST-332: Updating Lombiq.HelpfulLibraries.OrchardCore to 4.6.1-alpha.walma-15.1

---

Readme.md

NEST-355: Add note to Readme

---

src/Modules/OrchardCore.Commerce/Abstractions/IRegionService.cs
src/Modules/OrchardCore.Commerce/AdminMenu.cs
src/Modules/OrchardCore.Commerce/Drivers/AddressFieldDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/RegionSettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Extensions/RegionExtensions.cs
src/Modules/OrchardCore.Commerce/Models/RegionSettings.cs
src/Modules/OrchardCore.Commerce/Permissions.cs
src/Modules/OrchardCore.Commerce/Recipes/RegionTest.recipe.json
src/Modules/OrchardCore.Commerce/Services/RegionConfiguration.cs
src/Modules/OrchardCore.Commerce/Services/RegionService.cs
src/Modules/OrchardCore.Commerce/Startup.cs
src/Modules/OrchardCore.Commerce/ViewModels/AddressFieldViewModel.cs
src/Modules/OrchardCore.Commerce/ViewModels/RegionSettingsViewModel.cs
src/Modules/OrchardCore.Commerce/Views/AddressField_Edit.cshtml
src/Modules/OrchardCore.Commerce/Views/RegionSettings.Edit.cshtml
test/OrchardCore.Commerce.Tests.UI/Tests/RegionTests/PersistenceRegionSettingsTests.cs

OCC-88: Add site setting to limit the list of available countries/regions.

---

.github/workflows/create-jira-issues-for-community-activities.yml

Fixing some unfortunate copy-paste leftover.

Fixing create-jira-issues-for-community-activities workflow job name

---

src/Modules/OrchardCore.Commerce.ContentFields/Views/PriceField.Edit.cshtml

OCC-96: On the admin editor, Gross Price's currency is always the site's default currency

---

src/Libraries/OrchardCore.Commerce.MoneyDataType/Currency.cs
src/Libraries/OrchardCore.Commerce.MoneyDataType/KnownCurrencyTable.cs
test/OrchardCore.Commerce.Tests/CurrencyTests.cs

OCC-98: Currency sign is not displayed correctly because culture is not correct 

---

src/Modules/OrchardCore.Commerce/AdminMenu.cs
src/Modules/OrchardCore.Commerce/CommerceConstants.cs
src/Modules/OrchardCore.Commerce/Drivers/PriceVariantsPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Manifest.cs
src/Modules/OrchardCore.Commerce/Permissions.cs
src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Setup.recipe.json
src/Modules/OrchardCore.Commerce/Services/MoneyService.cs
src/Modules/OrchardCore.Commerce/Settings/CurrencySettings.cs
src/Modules/OrchardCore.Commerce/Settings/CurrencySettingsConfiguration.cs
src/Modules/OrchardCore.Commerce/Settings/CurrencySettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Settings/CurrencySettingsSelector.cs
src/Modules/OrchardCore.Commerce/Startup.cs
src/Modules/OrchardCore.Commerce/ViewModels/CurrencySettingsViewModel.cs
src/Modules/OrchardCore.Commerce/Views/CurrencySettings.Edit.cshtml
test/OrchardCore.Commerce.Tests/Fakes/TestMoneyService.cs
test/OrchardCore.Commerce.Tests/MoneyServiceTests.cs

OCC-100: Organizing Commerce settings menu items

---

src/Modules/OrchardCore.Commerce/Liquid/AmountConverterFilter.cs
src/Modules/OrchardCore.Commerce/Liquid/ToAmountConverterFilter.cs
src/Modules/OrchardCore.Commerce/Startup.cs

As the title says, exposed some viewmodels to liquid templates and added a filter that converts the JToken into the Amount struct. It's needed for liquid template overrides.

Adding some liquid support

---

Readme.md

ORCH-256: Adding demo video about Stripe Payment integration

---

src/Modules/OrchardCore.Commerce/Assets/Scripts/stripe-card-form.js
src/Modules/OrchardCore.Commerce/Assets/Styles/credit-card-form.scss
src/Modules/OrchardCore.Commerce/Views/StripeCheckout.cshtml

OCC-103: Some sort of loading sign feedback when clicking pay button

---

src/Modules/OrchardCore.Commerce/Assets/Scripts/stripe-card-form.js
src/Modules/OrchardCore.Commerce/Assets/Styles/credit-card-form.scss
src/Modules/OrchardCore.Commerce/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce/Controllers/UserController.cs
src/Modules/OrchardCore.Commerce/Drivers/AddressFieldDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Extensions/UpdateModelExtensions.cs
src/Modules/OrchardCore.Commerce/Views/AddressFieldEditor.cshtml
src/Modules/OrchardCore.Commerce/Views/Checkout.cshtml
src/Modules/OrchardCore.Commerce/Views/Payment/Index.cshtml
src/Modules/OrchardCore.Commerce/Views/StripeCheckout.cshtml

OCC-106: Checkout page form is not validated

---

src/Libraries/OrchardCore.Commerce.MoneyDataType/Currency.cs
src/Libraries/OrchardCore.Commerce.MoneyDataType/Currency.extra.cs
src/Libraries/OrchardCore.Commerce.MoneyDataType/Extensions/CultureInfoExtensions.cs
src/Libraries/OrchardCore.Commerce.MoneyDataType/KnownCurrencyTable.cs
test/OrchardCore.Commerce.Tests/CurrencyTests.cs

OCC-108: Replace en-EU culture with special EUR handling

---

src/Modules/OrchardCore.Commerce/Abstractions/IOrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Activities/OrderCreatedEvent.cs
src/Modules/OrchardCore.Commerce/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce/Drivers/OrderCreatedEventDisplay.cs
src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Helpers/OrderLineItemHelpers.cs
src/Modules/OrchardCore.Commerce/Liquid/OrderLineItemViewModelsConverterFilter.cs
src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Startup.cs
src/Modules/OrchardCore.Commerce/Views/Items/OrderCreatedEvent.Fields.Design.cshtml
src/Modules/OrchardCore.Commerce/Views/Items/OrderCreatedEvent.Fields.Thumbnail.cshtml

SITE-31: Reimplement not working workflows

---

src/Modules/OrchardCore.Commerce/Liquid/OrderLineItemViewModelsAndTaxRatesConverterFilter.cs
src/Modules/OrchardCore.Commerce/Models/ShoppingCartItem.cs
src/Modules/OrchardCore.Commerce/Services/PriceVariantProvider.cs
src/Modules/OrchardCore.Commerce/Startup.cs
test/OrchardCore.Commerce.Tests/ShoppingCartItemAttributeTests.cs

SITE-41: Reworking OrderLineItemViewModelsConverterFilter to also pass tax rates

---

src/Modules/OrchardCore.Commerce.ContentFields/Views/PriceField.Edit.cshtml

Bug in gross value in editor

---

.github/actions/spelling/allow.txt
.github/workflows/build-and-test.yml

OSOE-535: post-pull-request-checks-automation fails with personal access tokens with fine grained access

---

src/Modules/OrchardCore.Commerce/Startup.cs

NEST-402: Fix service registration.

---

src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Setup.recipe.json

[NEST-399](https://lombiq.atlassian.net/browse/NEST-399)

NEST-399: Check and perhaps hide certain setup recipes

---

mkdocs.yml

OCC-128: Documentation menu

---

Readme.md

ORCH-261: Adding demo video about the MVP

---

src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj

GOV-3: Updating Helpful Libraries to the latest stable version

---

src/Modules/OrchardCore.Commerce/Services/GlobalDiscountProvider.cs

OCC-136: Global Discounts: permision

---

src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs

SITE-48: Fixing NRE for discounts

---

src/Libraries/OrchardCore.Commerce.AddressDataType/OrchardCore.Commerce.AddressDataType.csproj
src/Libraries/OrchardCore.Commerce.MoneyDataType/OrchardCore.Commerce.MoneyDataType.csproj
src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce.Promotion/OrchardCore.Commerce.Promotion.csproj
src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj

[OCC-141](https://lombiq.atlassian.net/browse/OCC-141)
Fixes #273

OCC-141: Incorrect project website link in NuGet package

---

.gitignore
Directory.Build.props
src/Libraries/OrchardCore.Commerce.AddressDataType/OrchardCore.Commerce.AddressDataType.csproj
src/Libraries/OrchardCore.Commerce.MoneyDataType/OrchardCore.Commerce.MoneyDataType.csproj
src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce.Promotion/OrchardCore.Commerce.Promotion.csproj
src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj
src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj

OCC-140: No logo in the NuGet package

---

src/Libraries/OrchardCore.Commerce.MoneyDataType/Amount.cs
src/Libraries/OrchardCore.Commerce.MoneyDataType/Extensions/EnumerableExtensions.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs

SITE-50: Fixing rounding problems

---

docs/releases/1.1.0.md
mkdocs.yml

[OCC-148](https://lombiq.atlassian.net/browse/OCC-148)

OCC-148: Add new release to the docs

---

src/Libraries/OrchardCore.Commerce.MoneyDataType/OrchardCore.Commerce.MoneyDataType.csproj
src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce/Models/ShoppingCartCellViewModel.cs
src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj
src/Modules/OrchardCore.Commerce/Services/PriceService.cs
src/Modules/OrchardCore.Commerce/Services/StripePaymentService.cs
src/Modules/OrchardCore.Commerce/Views/StripeCheckout.cshtml
src/Modules/OrchardCore.Commerce/Views/Widget__ShoppingCartWidget.cshtml
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj
test/OrchardCore.Commerce.Tests.UI/Constants/ContentItemIds.cs
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/OrderSuccessTests.cs
test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj
test/OrchardCore.Commerce.Tests/PriceTests.cs

OCC-155
Fixes #291
This issue also contains some misc fixes for problems I found while preparing for my Orchard Harvest presentation.

OCC-155: Update packages

---

src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce.Promotion/OrchardCore.Commerce.Promotion.csproj
src/Modules/OrchardCore.Commerce.Tax/OrchardCore.Commerce.Tax.csproj
src/Modules/OrchardCore.Commerce/Assets/Scripts/toggle-second-address.js
src/Modules/OrchardCore.Commerce/Handlers/DiscountPartHandler.cs
src/Modules/OrchardCore.Commerce/Handlers/PricePartHandler.cs
src/Modules/OrchardCore.Commerce/Handlers/PriceVariantsPartHandler.cs
src/Modules/OrchardCore.Commerce/Handlers/SkuValidationHandler.cs
src/Modules/OrchardCore.Commerce/Handlers/TaxPartAndPricePartHandler.cs
src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/UserTests/UserPersistenceTests.cs
test/OrchardCore.Commerce.Tests/Fakes/FakeContentManager.cs
test/OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj

OCC-160: Upgrade to Orchard Core 1.6

---

src/Modules/OrchardCore.Commerce.Tax/Drivers/TaxRateSettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce.Tax/Models/TaxRateSettings.cs
src/Modules/OrchardCore.Commerce.Tax/Views/TaxRateSettings_Edit.cshtml
src/Modules/OrchardCore.Commerce/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce/Migrations/OrderMigrations.cs
src/Modules/OrchardCore.Commerce/Models/OrderPart.cs
src/Modules/OrchardCore.Commerce/Models/PromotionAndTaxProviderContext.cs
src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Samples.CustomTaxRates.recipe.json
src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Services/TaxRateTaxProvider.cs
src/Modules/OrchardCore.Commerce/Views/Checkout.cshtml

OCC-162: Handle taxes differently for corporations and private individuals.

---

.github/workflows/build-and-test.yml
src/Modules/OrchardCore.Commerce/Views/OrderPart.cshtml
src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_Product.cshtml
src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_Quantity.cshtml
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/BasicOrchardFeaturesTests/BasicOrchardFeaturesTests.cs
test/OrchardCore.Commerce.Tests.UI/UITestBase.cs

OCC-168: UI tests don't actually use the common configuration

---

.github/workflows/validate-pull-request.yml
OrchardCore.Commerce.sln
Readme.md
Reset-Local.ps1
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
src/OrchardCore.Commerce.Web/Program.cs
src/OrchardCore.Commerce.Web/appsettings.Development.json

[OCC-171](https://lombiq.atlassian.net/browse/OCC-171)
Also added a reset script and PR validation workflow.
Fixes #319

OCC-171: Configure Auto Setup

---

src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Extensions/ProductServiceExtensions.cs
src/Modules/OrchardCore.Commerce/Models/OrderLineItem.cs
src/Modules/OrchardCore.Commerce/Models/ShoppingCartItem.cs
src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs
src/Modules/OrchardCore.Commerce/Services/StripePaymentService.cs
src/Modules/OrchardCore.Commerce/ViewModels/OrderLineItemViewModel.cs
src/Modules/OrchardCore.Commerce/Views/OrderPart_Edit.cshtml

[OCC-65](https://lombiq.atlassian.net/browse/OCC-65)
Fixes #117

OCC-65: Make the line items editable in the OrderPart editor

---

.github/actions/spelling/allow/occ.txt
src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/BehaviorOrderTests.cs

[OCC-179](https://lombiq.atlassian.net/browse/OCC-179)
Fixes #329

OCC-179: Add missing UI tests for OrderPart editor

---

src/Modules/OrchardCore.Commerce/Controllers/ShoppingCartController.cs

[OCC-178](https://lombiq.atlassian.net/browse/OCC-178)
Fixes #328

OCC-178: User-friendly error if cookies can't be written and thus the shopping cart can't be managed

---

src/Modules/OrchardCore.Commerce.Inventory/Constants/FeatureIds.cs
src/Modules/OrchardCore.Commerce.Inventory/Manifest.cs
src/Modules/OrchardCore.Commerce/Abstractions/IProductEstimationContextUpdater.cs
src/Modules/OrchardCore.Commerce/Abstractions/IShoppingCartHelpers.cs
src/Modules/OrchardCore.Commerce/Drivers/DiscountPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/TaxRateTaxPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Models/ProductEstimationContext.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs
src/Modules/OrchardCore.Commerce/Settings/InventoryProductEstimationContextUpdater.cs
src/Modules/OrchardCore.Commerce/Startup.cs
test/OrchardCore.Commerce.Tests.UI/Extension/NotificationUITestContextExtenisons.cs
test/OrchardCore.Commerce.Tests.UI/Extension/NotificationUITestContextExtensions.cs
test/OrchardCore.Commerce.Tests.UI/Tests/LocalizedProductTests/LocalizedProductBehaviourTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/ProductBehaviourTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/WorkflowTests/WorkflowBehaviourTests.cs

[OCC-181](https://lombiq.atlassian.net/browse/OCC-181)
Fixes #336

OCC-181: Inventory warnings when listing content items in admin dashboard

---

src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj

[NEST-467](https://lombiq.atlassian.net/browse/NEST-467)

NEST-467: Update Lombiq.NodeJs.Extensions version to 1.3.0

---

src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Setup.recipe.json
src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Samples.Product.recipe.json
src/Modules/OrchardCore.Commerce/package.json
src/Modules/OrchardCore.Commerce/pnpm-lock.yaml
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/RetrievalProductTests.cs

[OCC-185](https://lombiq.atlassian.net/browse/OCC-185)
Fixes #343

OCC-185: Products listing page

---

src/Modules/OrchardCore.Commerce/package.json
src/Modules/OrchardCore.Commerce/pnpm-lock.yaml

[NEST-423](https://lombiq.atlassian.net/browse/NEST-423)

NEST-423: Updating packages

---

src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj
test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj

[NEST-423](https://lombiq.atlassian.net/browse/NEST-423)

NEST-423: Updating package

---

src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Development.Setup.recipe.json
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/ProductBehaviourTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/UserTests/UserPersistenceTests.cs

[OCC-191](https://lombiq.atlassian.net/browse/OCC-191)
Fixes #350

OCC-191: Add widget to the setup recipe to access the user address and user details pages

---

.github/workflows/build-and-test.yml

[OSOE-636](https://lombiq.atlassian.net/browse/OSOE-636)

OSOE-636: Updating to latest spelling action

---

src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeField.cshtml
src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeValue.cshtml
src/Modules/OrchardCore.Commerce/Views/NumericProductAttributeField.cshtml
src/Modules/OrchardCore.Commerce/Views/NumericProductAttributeValue.cshtml
src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_Product.cshtml
src/Modules/OrchardCore.Commerce/Views/TextProductAttributeValue.cshtml
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/ProductBehaviourTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/RetrievalProductTests.cs

[OCC-196](https://lombiq.atlassian.net/browse/OCC-196)
Fixes #366

OCC-196: Product Attributes should display the field label or name instead in cart and order display

---

Directory.Build.props
test/OrchardCore.Commerce.Tests.UI.Shortcuts/Controllers/OrderController.cs

[OSOE-179](https://lombiq.atlassian.net/browse/OSOE-179)

OSOE-179: Updating Analyzers to latest

---

src/Modules/OrchardCore.Commerce/package.json
src/Modules/OrchardCore.Commerce/pnpm-lock.yaml

[NEST-480](https://lombiq.atlassian.net/browse/NEST-480)

NEST-480: Update lock file

---

.github/workflows/publish-cloudsmith.yml

[OCC-197](https://lombiq.atlassian.net/browse/OCC-197)
Fixes #369

OCC-197: Revert publish-nuget.yml issue selector once https://github.com/Lombiq/GitHub-Actions/pull/270 is resolved.

---

src/Modules/OrchardCore.Commerce/Abstractions/IProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Abstractions/IProductAttributeService.cs
src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Extensions/ContentTypeDefinitionExtensions.cs
src/Modules/OrchardCore.Commerce/Models/OrderLineItem.cs
src/Modules/OrchardCore.Commerce/Models/ShoppingCartItem.cs
src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Samples.Order.recipe.json
src/Modules/OrchardCore.Commerce/Services/BooleanProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/NumericProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Services/ProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/ProductAttributeService.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartSerializer.cs
src/Modules/OrchardCore.Commerce/Services/StripePaymentService.cs
src/Modules/OrchardCore.Commerce/Services/TextProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Startup.cs
src/Modules/OrchardCore.Commerce/ViewModels/OrderLineItemViewModel.cs
src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeField.cshtml
src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeValue.cshtml
src/Modules/OrchardCore.Commerce/Views/OrderPart.cshtml
src/Modules/OrchardCore.Commerce/Views/OrderPart_Edit.cshtml
src/Modules/OrchardCore.Commerce/Views/ShoppingCartCell_Product.cshtml
src/Modules/OrchardCore.Commerce/Views/ShoppingCartWidgetPart.cshtml
test/OrchardCore.Commerce.Tests.UI/Extension/NavigationUITestContextExtensions.cs
test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/BehaviorOrderTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/ProductTests/RetrievalProductTests.cs

[OCC-195](https://lombiq.atlassian.net/browse/OCC-195)
Fixes #365

OCC-195: Boolean product attributes not stored in the order screen.

---

src/Modules/OrchardCore.Commerce/Settings/ProductAttributeFieldSettings.cs

[TDEAL-5](https://lombiq.atlassian.net/browse/TDEAL-5)

TDEAL-5: Fixing exception with null PredefinedValues

---

.gitattributes
Directory.Build.props
Readme.md
src/Libraries/OrchardCore.Commerce.Abstractions/OrchardCore.Commerce.Abstractions.csproj
src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce.Payment.Stripe/Migrations/StripeMigrations.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Models/StripePaymentProviderData.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Startup.cs
src/Modules/OrchardCore.Commerce.Payment/OrchardCore.Commerce.Payment.csproj
src/Modules/OrchardCore.Commerce/Assets/Styles/general/_error.scss
src/Modules/OrchardCore.Commerce/Assets/Styles/shopping-cart-widget.scss
src/Modules/OrchardCore.Commerce/Assets/Styles/shopping-cart.scss
src/Modules/OrchardCore.Commerce/Liquid/OrderLineItemViewModelsAndTaxRatesConverterFilter.cs
src/Modules/OrchardCore.Commerce/Services/OrderLineItemService.cs
src/Modules/OrchardCore.Commerce/Startup.cs
test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj

[NEST-504](https://lombiq.atlassian.net/browse/NEST-504)

NEST-504: Minor changes to include better in other projects

---

.github/workflows/build-and-test.yml
src/Libraries/OrchardCore.Commerce.Abstractions/Models/ShoppingCartItem.cs
src/Libraries/OrchardCore.Commerce.Abstractions/OrchardCore.Commerce.Abstractions.csproj
src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj
src/Modules/OrchardCore.Commerce.Inventory/OrchardCore.Commerce.Inventory.csproj
src/Modules/OrchardCore.Commerce.Payment/OrchardCore.Commerce.Payment.csproj
src/Modules/OrchardCore.Commerce/Controllers/ShoppingCartController.cs
src/Modules/OrchardCore.Commerce/Extensions/ProductServiceExtensions.cs
src/Modules/OrchardCore.Commerce/Services/BooleanProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/NumericProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/ProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Services/QueryStringAppliedProductListFilterParametersProvider.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartSerializer.cs
src/Modules/OrchardCore.Commerce/Services/TextProductAttributeProvider.cs
src/Modules/OrchardCore.Commerce/Views/ProductListPart.Filters.cshtml
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
src/OrchardCore.Commerce.Web/Program.cs
test/OrchardCore.Commerce.Tests.UI.Shortcuts/OrchardCore.Commerce.Tests.UI.Shortcuts.csproj
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/BasicOrchardFeaturesTests.cs
test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs

[TDEAL-16](https://lombiq.atlassian.net/browse/TDEAL-16)

TDEAL-16: Handle possible NREs caused by malicious POST requests.

---

src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs

[OSOE-767](https://lombiq.atlassian.net/browse/OSOE-767)

OSOE-767: Updating UI Testing Toolbox with ZAP HTML-SARIF report discrepancies fixed

---

src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentController.cs

[OCC-225](https://lombiq.atlassian.net/browse/OCC-225)
Fixes #413

OCC-225: Fixing ambiguous HTTP methods

---

.github/workflows/publish-cloudsmith.yml
.github/workflows/publish-nuget.yml

[OSOE-832](https://lombiq.atlassian.net/browse/OSOE-832)
to be merged after https://github.com/Lombiq/GitHub-Actions/pull/341

OSOE-832: Use release publish-nuget GHA workflow.

---

src/Libraries/OrchardCore.Commerce.Abstractions/Abstractions/IRegionService.cs
src/Libraries/OrchardCore.Commerce.Abstractions/Fields/AddressField.cs
src/Libraries/OrchardCore.Commerce.AddressDataType/Regions.cs
src/Modules/OrchardCore.Commerce.ContentFields/Drivers/AddressFieldDisplayDriver.cs
src/Modules/OrchardCore.Commerce.ContentFields/ViewModels/AddressFieldEditorViewModel.cs
src/Modules/OrchardCore.Commerce.ContentFields/Views/AddressFieldEditor.cshtml
src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce/Services/RegionService.cs

[OFFI-20](https://lombiq.atlassian.net/browse/OFFI-20)

OFFI-20: Add option to turn off parts of the AddressFieldEditor

---

src/Modules/OrchardCore.Commerce.ContentFields/Services/FieldsOnlyDisplayManager.cs

[OCC-237](https://lombiq.atlassian.net/browse/OCC-237)
Fixes #431

OCC-237: Checkout page throws exception because of non awaited async method

---

Directory.Packages.props
docs/features/exactly-payment.md
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
test/OrchardCore.Commerce.Tests.UI/OrchardCore.Commerce.Tests.UI.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/BasicOrchardFeaturesTests.cs
test/OrchardCore.Commerce.Tests.UI/UITestBase.cs
test/OrchardCore.Commerce.Tests.UI/orchardcore.htmlvalidate.json
test/OrchardCore.Commerce.Tests/CurrencyTests.cs

[OCC-252](https://lombiq.atlassian.net/browse/OCC-252)
Fixes #449

OCC-252: Target Orchard Core 1.8 in packages

---

src/Modules/OrchardCore.Commerce.Payment.Exactly/Services/ExactlyPaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment/Abstractions/IPaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce.Payment/Services/DummyPaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment/ViewModels/PaymentViewModel.cs

Save OrderPayment when needed for more situation

---

src/Modules/OrchardCore.Commerce.Payment.Stripe/Abstractions/IStripePaymentService.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/StripeController.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs

OCC-277: Get stripe confirm parameters async

---

src/Modules/OrchardCore.Commerce.Payment.Stripe/Abstractions/IStripePaymentService.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/StripeController.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/WebhookController.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs
src/Modules/OrchardCore.Commerce.Payment/Abstractions/IPaymentProvider.cs
src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentController.cs

Do not hard code shoppingCartId in the middle layer

---

Directory.Packages.props
src/Modules/OrchardCore.Commerce.ContentFields/Drivers/AddressFieldDisplayDriver.cs
src/Modules/OrchardCore.Commerce.ContentFields/Drivers/PriceFieldDisplayDriver.cs
src/Modules/OrchardCore.Commerce.ContentFields/Extensions/UpdateModelExtensions.cs
src/Modules/OrchardCore.Commerce.ContentFields/Settings/AddressFieldSettingsDriver.cs
src/Modules/OrchardCore.Commerce.ContentFields/Settings/PriceFieldSettingsDriver.cs
src/Modules/OrchardCore.Commerce.Inventory/Drivers/InventoryPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce.Payment.Exactly/Drivers/ExactlySettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Drivers/StripeApiSettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs
src/Modules/OrchardCore.Commerce.Tax/Drivers/TaxRateSettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/PriceDisplaySettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/PriceVariantsPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/ProductPartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/RegionSettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Drivers/TieredPricePartDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Settings/CurrencySettingsDisplayDriver.cs
src/Modules/OrchardCore.Commerce/Settings/ProductAttributeFieldSettingsDriver.cs

[OCC-280](https://lombiq.atlassian.net/browse/OCC-280)
`CreateModelAsync` everywhere it's possible, `CreateModelMaybeAsync` if there is authorization. Also `AddModelError` shortcut whenever possible.
Fixes #479

OCC-280: Use new HL extension methods

---

src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripePaymentService.cs

Make StripePaymentPart stronger

---

src/Modules/OrchardCore.Commerce.Payment/Abstractions/IPaymentService.cs
src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentController.cs
src/Modules/OrchardCore.Commerce.Payment/Services/PaymentService.cs
src/Modules/OrchardCore.Commerce/Endpoints/Services/ShoppingCartService.cs

Fixes #495, and Abstract the logic of Validate

Fixes a error of Update API

---

Directory.Packages.props
src/Modules/OrchardCore.Commerce.Payment.Stripe/OrchardCore.Commerce.Payment.Stripe.csproj

[OFFI-85](https://lombiq.atlassian.net/browse/OFFI-85)

OFFI-85: Update package to fix NuGet high sec vuln warning

---

src/Modules/OrchardCore.Commerce.ContentFields/pnpm-lock.yaml
src/Modules/OrchardCore.Commerce.Payment.Stripe/Assets/Scripts/stripe-payment-form.js
src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/StripeController.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/pnpm-lock.yaml
src/Modules/OrchardCore.Commerce.Payment/pnpm-lock.yaml
src/Modules/OrchardCore.Commerce/pnpm-lock.yaml

[TDEAL-42](https://lombiq.atlassian.net/issues/TDEAL-42)
Fixes #505

TDEAL-42: Fix Stripe serialization and revert lockfileVersion

---

.github/workflows/build-and-test.yml
.readthedocs.yml

[INFRA-164](https://lombiq.atlassian.net/browse/INFRA-164)

INFRA-164: GHA runner OS version pinning

---

src/Modules/OrchardCore.Commerce.Payment.Stripe/Handlers/SubscriptionStripeWebhookEventHandler.cs

[OFFI-221](https://lombiq.atlassian.net/browse/OFFI-221)

OFFI-221: Fixing subscription end date

---

src/Modules/OrchardCore.Commerce/OrchardCore.Commerce.csproj
src/Modules/OrchardCore.Commerce/Package.Build.props

[OCC-257](https://lombiq.atlassian.net/browse/OCC-257)
Fixes #456

OCC-257: Implement custom Package.Build.props file that declares NuGet dependencies as ModulePackageNames.

---

docs/releases/3.0.0.md

[OCC-309](https://lombiq.atlassian.net/browse/OCC-309)

OCC-309: Add notes about new features in this release.

---

.vscode/launch.json
.vscode/tasks.json
Directory.Packages.props
package.json
src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/WebhookController.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Migrations/StripeMigrations.cs
src/Modules/OrchardCore.Commerce.Payment/Controllers/PaymentBaseController.cs
src/Modules/OrchardCore.Commerce/Controllers/ShoppingCartController.cs
src/Modules/OrchardCore.Commerce/Drivers/DiscountPartDisplayDriver.cs
src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj
test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs

[OCC-313](https://lombiq.atlassian.net/browse/OCC-313)
Fixes #524

OCC-313: Update NuGet package versions to fix PNPM problem

---

src/Modules/OrchardCore.Commerce/Controllers/ShoppingCartController.cs
src/Modules/OrchardCore.Commerce/Endpoints/Services/IShoppingCartService.cs
src/Modules/OrchardCore.Commerce/Endpoints/Services/ShoppingCartService.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs
test/OrchardCore.Commerce.Tests/ShoppingCartControllerTests.cs

Should use parsedLine instead of item for AddItemAndGetCartAsync

---

docs/releases/3.0.0.md
src/Modules/OrchardCore.Commerce.Payment.Stripe/Handlers/SubscriptionStripeWebhookEventHandler.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/DummyCustomerService.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripeCustomerService.cs

[OFFI-257](https://lombiq.atlassian.net/browse/OFFI-257)

OFFI-257: Handling null data

---

src/Modules/OrchardCore.Commerce.Payment.Stripe/Controllers/StripeController.cs

[OCC-331](https://lombiq.atlassian.net/browse/OCC-331)
Fixes #544

OCC-331: Fix stripe URL.

---

Directory.Packages.props

[OCC-332](https://lombiq.atlassian.net/browse/OCC-332)
Fixes #546

OCC-332: Update packages

---

.github/workflows/renovate.yml
OrchardCore.Commerce.sln
renovate.json5

[OCC-315](https://lombiq.atlassian.net/browse/OCC-315)
Fixes #528

OCC-315: Add Renovate dependency updates

---

Directory.Packages.props
package.json
renovate.json5
src/Modules/OrchardCore.Commerce.Payment.Stripe/Abstractions/IStripeSubscriptionService.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Endpoints/Api/StripeSubscriptionEndpoint.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Handlers/DefaultStripeWebhookEventHandler.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Handlers/SubscriptionStripeWebhookEventHandler.cs
src/Modules/OrchardCore.Commerce.Payment.Stripe/Services/StripeSubscriptionService.cs

[OCC-315](https://lombiq.atlassian.net/browse/OCC-315)
Previous PRs associated with this issue: #555 #556
We will soon remove NodeJS.Extensions so all the related PRs were rejected: #557 #560 #561 #562 #564 #565 #566
Fixes #558
Fixes #559
Fixes #563

OCC-315: Update dependencies

---

src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj

Update OC to 2.1.7

---

src/Libraries/OrchardCore.Commerce.Abstractions/Models/ShoppingCartItem.cs
src/Modules/OrchardCore.Commerce/Abstractions/IShoppingCartSerializer.cs
src/Modules/OrchardCore.Commerce/Models/DeserializeResult.cs
src/Modules/OrchardCore.Commerce/Services/SessionShoppingCartPersistence.cs
src/Modules/OrchardCore.Commerce/Services/ShoppingCartSerializer.cs
test/OrchardCore.Commerce.Tests/Extensions/CommerceAutoMockerExtensions.cs
test/OrchardCore.Commerce.Tests/ProductAttributeTests.cs
test/OrchardCore.Commerce.Tests/SerializationTests.cs
test/OrchardCore.Commerce.Tests/ShoppingCartControllerTests.cs

[OCC-361](https://lombiq.atlassian.net/browse/OCC-361)
Fixes #606

OCC-361: The shopping cart throws KeyNotFoundException

---

.github/workflows/build-and-test.yml

[OSOE-1160](https://lombiq.atlassian.net/browse/OSOE-1160)

OSOE-1160: Change default node package manager caching behavior in GHA
